### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by aclavin-eab** [hhalterman/Responsive-Portfolio#1]
Sites look great! Some minor inconsistencies in your indentation in your html, also you are loading scripts at the end of your html document which is great!.. but be careful about loading libraries there, generally only runtime scripts are loaded at the end of the page and libraries are loaded in the head because you may need certain things from them to get the page behaving properly... where as runtime scripts will do things to the page so the page needs to be there before them; it's a complicated distinction you don't need to worry about right now, just know if something isn't working you might be loading your javascript files at the wrong time. Also, avoid using !important if you can, it's kind of the nuclear option, there are many other better ways to increase your specificity to get your rules to work... but kudos on using some libraries on your site. (and when you have to use them it's general best practice to put a space between your rule's value and the !important tag)

**Comment by aclavin-eab** [comment]
Oh also, you want to stay away from setting pixel widths when designing responsively, and your small class you want to go all the way down to 0 usually (setting it as a media query for a max-width instead of a min-width, not actually specifying min width of 0)

**Comment by hhalterman** [comment]
Awesome! Thanks for all the feedback! I really appreciate it.

I struggled with where to put the scripts. The bootstrap site says to load them at the end of your document even though I normally put them in the head. So I tried both, but the bootstrap toggle function on the navbar would only work if the scripts were at the end of the document. I will definitely investigate that some more! Thanks for the tips.

I know the !important is not the best to use, but I was struggling to overwrite the bootstrap css. It didn't dawn on me that I should have used a CSS reset until Sunday lol. LESSON LEARNED!!

I totally swore someone told us to use min-width instead of max-width in order to design to mobile first, but I can't find anything in slack or my notes about it so I might just be crazy. I originally had written the media queries using max-width, so I will just revert to my old ways!

**Comment by aclavin-eab** [comment]
Hmm, if the bootstrap documentation says to do it that way, definitely you are right in doing it that way. That makes sense, if the buttons aren't already present in the document when the scripts load (they would be if they are in the script after the button, wouldn't be if before) they can't attach functionality to it. Another fancy thing to play with is the async attribute on a script, you might be able to put it in your head if you put the async attribute on it, but nothing wrong with putting it at the end especially if documentation tells you to. 

so if something in bootstrap is told by one class to do something (.class {rule: value}) you need to achieve higher specificity, you could do this by important, which you did, but a better way to do it would be say... two classes (.parentElementClass .class{rule: value}); however bootstrap might already be using more specificity than 2 classes, you can always check in the browser by inspecting the element and reading what the rules applied to it are set up selector wise like.

As far as the max-width, only your smallest style should be on max-width, all of the others should be min-width, there are alot of opinions on how to do this, but yours wasn't applying the classes it seemed you wanted anytime it gotter smaller than whatever your smallest min width was, it all the sudden went back to the rules that weren't in a media-query, which i think seemed to be geared for a large page width... or at least not specifically catered to a small one.

**Comment by aclavin-eab** [comment]
oh also, this idea of "specificity"; it's everything in css, once you understand the nuances of how css calculates specificity you understand the biggest part of it, everything after that is just practice and knowing specific syntax or the documentation where to find it
